# Generated by Django 5.1.5 on 2026-04-30 10:07

import django.db.models.deletion
import morest.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BearerToken",
            fields=[
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "key",
                    models.CharField(
                        default=morest.utils.generate_api_token,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Key",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bearer_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bearer Token",
                "verbose_name_plural": "Bearer Tokens",
                "abstract": False,
                "unique_together": {("title", "user")},
            },
        ),
    ]
